// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ommo_service_api.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ommo {
  public static partial class CoreService
  {
    static readonly string __ServiceName = "ommo.CoreService";

    static readonly grpc::Marshaller<global::Ommo.TrackingDevicesRequest> __Marshaller_ommo_TrackingDevicesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.TrackingDevicesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.TrackingDevices> __Marshaller_ommo_TrackingDevices = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.TrackingDevices.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.TrackingDeviceDataStreamRequest> __Marshaller_ommo_TrackingDeviceDataStreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.TrackingDeviceDataStreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.TrackingDeviceData> __Marshaller_ommo_TrackingDeviceData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.TrackingDeviceData.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.TrackingDevicesEventStreamRequest> __Marshaller_ommo_TrackingDevicesEventStreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.TrackingDevicesEventStreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.TrackingDeviceEvent> __Marshaller_ommo_TrackingDeviceEvent = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.TrackingDeviceEvent.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.DataFrameStreamRequest> __Marshaller_ommo_DataFrameStreamRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.DataFrameStreamRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ommo.DataFrame> __Marshaller_ommo_DataFrame = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ommo.DataFrame.Parser.ParseFrom);

    static readonly grpc::Method<global::Ommo.TrackingDevicesRequest, global::Ommo.TrackingDevices> __Method_GetTrackingDevices = new grpc::Method<global::Ommo.TrackingDevicesRequest, global::Ommo.TrackingDevices>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTrackingDevices",
        __Marshaller_ommo_TrackingDevicesRequest,
        __Marshaller_ommo_TrackingDevices);

    static readonly grpc::Method<global::Ommo.TrackingDeviceDataStreamRequest, global::Ommo.TrackingDeviceData> __Method_OpenTrackingDeviceDataStream = new grpc::Method<global::Ommo.TrackingDeviceDataStreamRequest, global::Ommo.TrackingDeviceData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "OpenTrackingDeviceDataStream",
        __Marshaller_ommo_TrackingDeviceDataStreamRequest,
        __Marshaller_ommo_TrackingDeviceData);

    static readonly grpc::Method<global::Ommo.TrackingDevicesEventStreamRequest, global::Ommo.TrackingDeviceEvent> __Method_OpenTrackingDevicesEventStream = new grpc::Method<global::Ommo.TrackingDevicesEventStreamRequest, global::Ommo.TrackingDeviceEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "OpenTrackingDevicesEventStream",
        __Marshaller_ommo_TrackingDevicesEventStreamRequest,
        __Marshaller_ommo_TrackingDeviceEvent);

    static readonly grpc::Method<global::Ommo.DataFrameStreamRequest, global::Ommo.DataFrame> __Method_OpenDataFrameStream = new grpc::Method<global::Ommo.DataFrameStreamRequest, global::Ommo.DataFrame>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "OpenDataFrameStream",
        __Marshaller_ommo_DataFrameStreamRequest,
        __Marshaller_ommo_DataFrame);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ommo.OmmoServiceApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CoreService</summary>
    [grpc::BindServiceMethod(typeof(CoreService), "BindService")]
    public abstract partial class CoreServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Ommo.TrackingDevices> GetTrackingDevices(global::Ommo.TrackingDevicesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task OpenTrackingDeviceDataStream(global::Ommo.TrackingDeviceDataStreamRequest request, grpc::IServerStreamWriter<global::Ommo.TrackingDeviceData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task OpenTrackingDevicesEventStream(global::Ommo.TrackingDevicesEventStreamRequest request, grpc::IServerStreamWriter<global::Ommo.TrackingDeviceEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task OpenDataFrameStream(global::Ommo.DataFrameStreamRequest request, grpc::IServerStreamWriter<global::Ommo.DataFrame> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CoreService</summary>
    public partial class CoreServiceClient : grpc::ClientBase<CoreServiceClient>
    {
      /// <summary>Creates a new client for CoreService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CoreServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CoreService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CoreServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CoreServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CoreServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ommo.TrackingDevices GetTrackingDevices(global::Ommo.TrackingDevicesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTrackingDevices(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ommo.TrackingDevices GetTrackingDevices(global::Ommo.TrackingDevicesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTrackingDevices, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ommo.TrackingDevices> GetTrackingDevicesAsync(global::Ommo.TrackingDevicesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTrackingDevicesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ommo.TrackingDevices> GetTrackingDevicesAsync(global::Ommo.TrackingDevicesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTrackingDevices, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ommo.TrackingDeviceData> OpenTrackingDeviceDataStream(global::Ommo.TrackingDeviceDataStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenTrackingDeviceDataStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ommo.TrackingDeviceData> OpenTrackingDeviceDataStream(global::Ommo.TrackingDeviceDataStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_OpenTrackingDeviceDataStream, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ommo.TrackingDeviceEvent> OpenTrackingDevicesEventStream(global::Ommo.TrackingDevicesEventStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenTrackingDevicesEventStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ommo.TrackingDeviceEvent> OpenTrackingDevicesEventStream(global::Ommo.TrackingDevicesEventStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_OpenTrackingDevicesEventStream, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ommo.DataFrame> OpenDataFrameStream(global::Ommo.DataFrameStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return OpenDataFrameStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Ommo.DataFrame> OpenDataFrameStream(global::Ommo.DataFrameStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_OpenDataFrameStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CoreServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CoreServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CoreServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetTrackingDevices, serviceImpl.GetTrackingDevices)
          .AddMethod(__Method_OpenTrackingDeviceDataStream, serviceImpl.OpenTrackingDeviceDataStream)
          .AddMethod(__Method_OpenTrackingDevicesEventStream, serviceImpl.OpenTrackingDevicesEventStream)
          .AddMethod(__Method_OpenDataFrameStream, serviceImpl.OpenDataFrameStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CoreServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetTrackingDevices, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ommo.TrackingDevicesRequest, global::Ommo.TrackingDevices>(serviceImpl.GetTrackingDevices));
      serviceBinder.AddMethod(__Method_OpenTrackingDeviceDataStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ommo.TrackingDeviceDataStreamRequest, global::Ommo.TrackingDeviceData>(serviceImpl.OpenTrackingDeviceDataStream));
      serviceBinder.AddMethod(__Method_OpenTrackingDevicesEventStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ommo.TrackingDevicesEventStreamRequest, global::Ommo.TrackingDeviceEvent>(serviceImpl.OpenTrackingDevicesEventStream));
      serviceBinder.AddMethod(__Method_OpenDataFrameStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ommo.DataFrameStreamRequest, global::Ommo.DataFrame>(serviceImpl.OpenDataFrameStream));
    }

  }
}
#endregion
